title: ManyMusic🎵
description: ManyMusic Dataset 
theme: just-the-docs

url: https://manymusic.net

aux_links:
  Paper: https://arxiv.org/abs/2401.12345
  Zenodo: https://zenodo.org/record/1234567
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-default-layout