title: ManyMusic🎵
description: ManyMusic Dataset 
theme: just-the-docs
# color_scheme: dark

url: https://manymusic.net

aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
