title: ManyMusic🎵
description: ManyMusic Dataset 
theme: just-the-docs

# url: https://manymusic.net
url: https://seunggookim.github.io/manymusic-stim/

aux_links:
  Paper: https://arxiv.org/abs/2401.12345
  Zenodo: https://zenodo.org/record/1234567
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# plugins:
#   - jekyll-default-layout

ga_tracking: G-E9Z6Q1YYX2
ga_tracking_anonymize_ip: true
